version: "3.9"
services:
  image-service:
    build:
      context: ./imageService/
    container_name: safesites-image-service
    ports:
      - 5201:81
    restart: always

  hate-speech-service:
    build:
      context: ./hateSpeechService/
    container_name: safesites-hate-speech-service
    ports:
      - 5202:5000
    restart: always

  backend-service:
    build:
      context: ./server/
    container_name: safesites-backend-service
    ports:
      - 5200:80
    restart: always
    environment:
      - HATE_SERVICE_ID=hate-speech-service
      - HATE_SERVICE_PORT=5000
      - IMAGE_PROCESSOR_ID=image-service
      - IMAGE_PROCESSOR_PORT=81
      - PATH_TO_STATIC=/static
    volumes:
      - static-volume:/static

  client:
    build:
      context: ./client/
    container_name: safesites-client
    volumes:
      - static-volume:/static
    command: tail -F anything
  
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static-volume:/static
volumes:
  static-volume: